### ISSUE TITLE
Could not compile code

### ISSUE THREAD

**Issue by brianerdelyi** [dapphub/ds-token#13]
I'm sure I'm doing something wrong... but not sure what.

Trying to compile token.sol and it fails at the import statements.

**Comment by dbrock** [comment]
Are you using `dapp`? (See http://dapp.tools)

**Comment by brianerdelyi** [comment]
No, I was using the Ethereum Wallet.

Brian

**Comment by rainbreak** [comment]
@brianerdelyi the import statements are processed by `dapp` to convert them into real paths. You won't be able to compile unless you copy everything into a single file first.

Single file conversion is an upcoming feature of `dapp`: https://github.com/dapphub/dapp/issues/32. But until then it'll have to be by hand.

**Comment by dbrock** [comment]
Not really "processed by `dapp`" though... that seems like an overstatement (and it happens to be what `dapple` used to do). I think this should be added as a feature to `solc` and then we use that from `dapp`. We're not doing any mangling or parsing of source code right now and it would be nice to keep it that way. Do you agree @rainbreak?

**Comment by brianerdelyi** [comment]
I'm not using app tools so I'll look into that.  Otherwise, I'll paste into a single file and compile with the Ethereum wallet.

**Comment by nmushegian** [comment]
lmk if you need more help
